# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9a5b1235184f0abba6334487b2133e28fb702d838016cbe08c9f1a958a67f1493cc6fdaa727ae5fa2730315eb9745dac2ba4b990e68d14157c6da77c29f45e6
  last_fm_key: <%= ENV["LAST_FM_KEY"] %>

test:
  secret_key_base: a2094371023c024cf0b039654a44768719832fbece8b84077750fe349393b607a4f50615018f6fc93774d83ded067ffed05d191b052c2f56e4487cddd56b8f6a
  last_fm_key: <%= ENV["LAST_FM_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  last_fm_key: <%= ENV["LAST_FM_KEY"] %>
